{
  "errorMessage": "Float types are not supported. Use Decimal types instead.",
  "errorType": "TypeError",
  "requestId": "849a55cc-0222-4b81-b193-6c25109a37c5",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 75, in lambda_handler\n    ACOMP_TABLE.update_item(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/boto3/resources/factory.py\", line 581, in do_action\n    response = action(self, *args, **kwargs)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/boto3/resources/action.py\", line 88, in __call__\n    response = getattr(parent.meta.client, operation_name)(*args, **params)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/client.py\", line 602, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/context.py\", line 123, in wrapper\n    return func(*args, **kwargs)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/client.py\", line 1019, in _make_api_call\n    api_params = self._emit_api_params(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/client.py\", line 1138, in _emit_api_params\n    self.meta.events.emit(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/hooks.py\", line 412, in emit\n    return self._emitter.emit(aliased_event_name, **kwargs)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/hooks.py\", line 256, in emit\n    return self._emit(event_name, kwargs)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/hooks.py\", line 239, in _emit\n    response = handler(**kwargs)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/boto3/dynamodb/transform.py\", line 217, in inject_attribute_value_input\n    self._transformer.transform(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/boto3/dynamodb/transform.py\", line 289, in transform\n    self._transform_parameters(model, params, transformation, target_shape)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/boto3/dynamodb/transform.py\", line 296, in _transform_parameters\n    getattr(self, f'_transform_{type_name}')(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/boto3/dynamodb/transform.py\", line 312, in _transform_structure\n    self._transform_parameters(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/boto3/dynamodb/transform.py\", line 296, in _transform_parameters\n    getattr(self, f'_transform_{type_name}')(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/boto3/dynamodb/transform.py\", line 326, in _transform_map\n    params[key] = transformation(value)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/boto3/dynamodb/types.py\", line 114, in serialize\n    dynamodb_type = self._get_dynamodb_type(value)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/boto3/dynamodb/types.py\", line 127, in _get_dynamodb_type\n    elif self._is_number(value):\n",
    "  File \"/var/lang/lib/python3.11/site-packages/boto3/dynamodb/types.py\", line 171, in _is_number\n    raise TypeError(\n"
  ]
}
